apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: test-awx-replicas
  namespace: awx
spec:
  replicas: 0
  #service_type: nodeport
  #ingress_type: none
  service_type: LoadBalancer
  loadbalancer_protocol: http
  loadbalancer_port: 8081
  ee_images:
  - name: test-environment-with-harbor
    image: poc.yahanjunho.tk:4443/library/awx-ee:latest
  control_plane_ee_image: poc.yahanjunho.tk:4443/library/awx-ee:latest
