apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-01
  namespace: awx
spec:
  replicas: 2
  #service_type: nodeport
  #ingress_type: none
  service_type: LoadBalancer
  loadbalancer_protocol: http
  loadbalancer_port: 8080
